### ISSUE TITLE
Warning about the usage of defaultProps 

### ISSUE THREAD

**Issue by quiet-node** [pacocoursey/next-themes#170]
I'm running next-themes v0.2.1 on Next@13.2.4 (appDir), tailwindCSS@3.2.2 and got this warning every time in dev mode.

```
Warning: Unknown: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at v.disableBaseline (webpack-internal:///(sc_client)/./node_modules/@nextui-org/react/cjs/theme/theme-provider.js:1:2034)
    at Lazy
    at m (webpack-internal:///(sc_client)/./node_modules/next-themes/dist/index.js:1:335)
    at exports.ThemeProvider (webpack-internal:///(sc_client)/./node_modules/next-themes/dist/index.js:1:3636)
    at Lazy
    at Provider (webpack-internal:///(sc_client)/./node_modules/react-redux/lib/components/Provider.js:19:3)
    at Lazy
    at div
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:61:9)
    at HotReload (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:22)
    at Router (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:45:23)
    at ErrorBoundaryHandler (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:57:9)
    at ErrorBoundary (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/error-boundary.js:69:26)
    at AppRouter (webpack-internal:///(sc_client)/./node_modules/next/dist/client/components/app-router.js:23:13)
    at Lazy
    at Lazy
    at ServerComponentWrapper (/Users/january/Development/SYNS/client/node_modules/next/dist/server/app-render.js:305:28)
    at ServerComponentWrapper (/Users/january/Development/SYNS/client/node_modules/next/dist/server/app-render.js:305:28)
    at InsertedHTML (/Users/january/Development/SYNS/client/node_modules/next/dist/server/app-render.js:1173:33)
```

Any ideas?

**Comment by pacocoursey** [comment]
As the error tells you, something in `@nextui-org/react` is using `defaultProps`.

```
 v.disableBaseline (webpack-internal:///(sc_client)/./node_modules/@nextui-org
```

You should open an issue there instead: https://github.com/nextui-org/nextui/issues
